### ISSUE TITLE
Installation: MongoDB no longer has a Release file

### ISSUE THREAD

**Issue by joaociocca** [picoCTF/picoCTF#458] opened 2020-05-06 15:05 UTC
I tried to install this for the first time to mess around and...

```
TASK [pico-web : Setup nodejs repositories] ************************************
fatal: [dev_web]: FAILED! => {"changed": true, "cmd": "/tmp/node_setup.sh", "delta": "0:00:24.752977", "end": "2020-05-06 14:54:47.981446", "msg": "non-zero return code", "rc": 1, "start": "2020-05-06 14:54:23.228469", "stderr": "E: The repository 'http://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 Release' no longer has a Release file.", "stderr_lines": ["E: The repository 'http://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 Release' no longer has a Release file."], "stdout": "\n================================================================================\n================================================================================\n\n                              DEPRECATION WARNING                            \n\n  Node.js 8.x LTS Carbon is no longer actively supported!\n\n  You will not receive security or critical stability updates for this version.\n\n  You should migrate to a supported version of Node.js as soon as possible.\n  Use the installation script that corresponds to the version of Node.js you\n  wish to install. e.g.\n\n   * https://deb.nodesource.com/setup_10.x — Node.js 10 LTS \"Dubnium\" (recommended)\n   * https://deb.nodesource.com/setup_12.x — Node.js 12 LTS \"Erbium\"\n\n  Please see https://github.com/nodejs/Release for details about which\n  version may be appropriate for you.\n\n  The NodeSource Node.js distributions repository contains\n  information both about supported versions of Node.js and supported Linux\n  distributions. To learn more about usage, see the repository:\n    https://github.com/nodesource/distributions\n\n================================================================================\n================================================================================\n\nContinuing in 20 seconds ...\n\n\n## Installing the NodeSource Node.js 8.x LTS Carbon repo...\n\n\n## Populating apt-get cache...\n\n+ apt-get update\nHit:1 http://archive.ubuntu.com/ubuntu bionic InRelease\nHit:2 http://security.ubuntu.com/ubuntu bionic-security InRelease\nHit:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease\nHit:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease\nIgn:5 http://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 InRelease\nErr:6 http://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 Release\n  Cannot initiate the connection to repo.mongodb.org:80 (2600:9000:213b:bc00:1e:e933:980a:3ba1). - connect (101: Network is unreachable) Cannot initiate the connection to repo.mongodb.org:80 (2600:9000:213b:cc00:1e:e933:980a:3ba1). - connect (101: Network is unreachable) Cannot initiate the connection to repo.mongodb.org:80 (2600:9000:213b:8200:1e:e933:980a:3ba1). - connect (101: Network is unreachable) Cannot initiate the connection to repo.mongodb.org:80 (2600:9000:213b:7a00:1e:e933:980a:3ba1). - connect (101: Network is unreachable) Cannot initiate the connection to repo.mongodb.org:80 (2600:9000:213b:d400:1e:e933:980a:3ba1). - connect (101: Network is unreachable) Cannot initiate the connection to repo.mongodb.org:80 (2600:9000:213b:ae00:1e:e933:980a:3ba1). - connect (101: Network is unreachable) Cannot initiate the connection to repo.mongodb.org:80 (2600:9000:213b:3800:1e:e933:980a:3ba1). - connect (101: Network is unreachable) Cannot initiate the connection to repo.mongodb.org:80 (2600:9000:213b:800:1e:e933:980a:3ba1). - connect (101: Network is unreachable)\nReading package lists...\nError executing command, exiting", "stdout_lines": ["", "================================================================================", "================================================================================", "", "                              DEPRECATION WARNING                            ", "", "  Node.js 8.x LTS Carbon is no longer actively supported!", "", "  You will not receive security or critical stability updates for this version.", "", "  You should migrate to a supported version of Node.js as soon as possible.", "  Use the installation script that corresponds to the version of Node.js you", "  wish to install. e.g.", "", "   * https://deb.nodesource.com/setup_10.x — Node.js 10 LTS \"Dubnium\" (recommended)", "   * https://deb.nodesource.com/setup_12.x — Node.js 12 LTS \"Erbium\"", "", "  Please see https://github.com/nodejs/Release for details about which", "  version may be appropriate for you.", "", "  The NodeSource Node.js distributions repository contains", "  information both about supported versions of Node.js and supported Linux", "  distributions. To learn more about usage, see the repository:", "    https://github.com/nodesource/distributions", "", "================================================================================", "================================================================================", "", "Continuing in 20 seconds ...", "", "", "## Installing the NodeSource Node.js 8.x LTS Carbon repo...", "", "", "## Populating apt-get cache...", "", "+ apt-get update", "Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease", "Hit:2 http://security.ubuntu.com/ubuntu bionic-security InRelease", "Hit:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease", "Hit:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease", "Ign:5 http://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 InRelease", "Err:6 http://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 Release", "  Cannot initiate the connection to repo.mongodb.org:80 (2600:9000:213b:bc00:1e:e933:980a:3ba1). - connect (101: Network is unreachable) Cannot initiate the connection to repo.mongodb.org:80 (2600:9000:213b:cc00:1e:e933:980a:3ba1). - connect (101: Network is unreachable) Cannot initiate the connection to repo.mongodb.org:80 (2600:9000:213b:8200:1e:e933:980a:3ba1). - connect (101: Network is unreachable) Cannot initiate the connection to repo.mongodb.org:80 (2600:9000:213b:7a00:1e:e933:980a:3ba1). - connect (101: Network is unreachable) Cannot initiate the connection to repo.mongodb.org:80 (2600:9000:213b:d400:1e:e933:980a:3ba1). - connect (101: Network is unreachable) Cannot initiate the connection to repo.mongodb.org:80 (2600:9000:213b:ae00:1e:e933:980a:3ba1). - connect (101: Network is unreachable) Cannot initiate the connection to repo.mongodb.org:80 (2600:9000:213b:3800:1e:e933:980a:3ba1). - connect (101: Network is unreachable) Cannot initiate the connection to repo.mongodb.org:80 (2600:9000:213b:800:1e:e933:980a:3ba1). - connect (101: Network is unreachable)", "Reading package lists...", "Error executing command, exiting"]}
        to retry, use: --limit @/picoCTF/ansible/site.retry

PLAY RECAP *********************************************************************
dev_web                    : ok=37   changed=23   unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

Considering the length of that line, I probably should highlight this:

```
"stderr": "E: The repository 'http://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 Release' no longer has a Release file."
```

Guess I should point that I have zero experience with Vagrant... but if anyone more knowledgeable points that it's an easy thing to fix, I'm up for trying to learn how to.

**Comment by hiliang-cmu** [comment] 2020-05-06 15:51
Seems like you're seeing some odd network issues, 

> `Cannot initiate the connection to repo.mongodb.org:80 (2600:9000:213b:bc00:1e:e933:980a:3ba1). - connect (101: Network is unreachable)`

Whereas http://repo.mongodb.org/ is definitely up as of this moment. In fact, this task for `Setup nodejs repositories` happens quite a bit after the mongodb installation tasks (which presumably succeeded)

I assume you have latest vagrant and virtualbox installed? What OS?

Try `vagrant destroy`ing the box and restart the process. 

There has been a recent mention somewhere on discord of some network-related issues during installation, might have to start tracking if this is some new virtualbox problem.

**Comment by joaociocca** [comment] 2020-05-06 17:15
I do understand it could be a network problem, but from my browser, even though repo.mongodb.org is accessible, the Release link returns 404

![image](https://user-images.githubusercontent.com/6473725/81207310-c376b780-8fa3-11ea-9076-a3882a1c65ff.png)

![image](https://user-images.githubusercontent.com/6473725/81207337-cc678900-8fa3-11ea-8e94-235706069d8b.png)

Destroying now... while retry.
```
PS D:\projetos\picoCTF> vagrant destroy
    web: Are you sure you want to destroy the 'web' VM? [y/N] y
==> web: Forcing shutdown of VM...
==> web: Destroying VM and associated drives...
    shell: Are you sure you want to destroy the 'shell' VM? [y/N] y
==> shell: Forcing shutdown of VM...
==> shell: Destroying VM and associated drives...
PS D:\projetos\picoCTF>
```

**Comment by hiliang-cmu** [comment] 2020-05-08 18:22
> Looks like I'm getting random network errors... is there a way to retry, instead of just destroy and restart from scratch?

`vagrant up --provision`

Yeah definitely weird networking because comes and goes between task to task in the playbook.

**Comment by dmartin** [comment] 2020-05-21 22:47
Seems like this is likely a networking/VM issue rather than the application, so closing this for now. We can reopen to investigate further if this is reproducible.

**Closed by dmartin** 2020-05-21 22:47 UTC
